### ISSUE TITLE
Awesome introduction to ecs

### ISSUE THREAD

**Issue by sabriboughanmi** [davidpol/SurvivalShooterECS#3]
Hi,
it's a great introduction to ecs but i think a lot of your systems can be better by using the JobComponentSystem, like Camera follow ...

**Comment by davidpol** [comment]
Thank you!

Most of the systems touch traditional Unity game objects, so unfortunately cannot be multithreaded via job systems. As the ECS evolves and provides access to more engine features, more code will be able to be moved to job systems.

**Comment by Opeth001** [comment]
im currently creating a new Game using ECS + Some Pure Systems.
for the Camera i did a Full pure System, in case if you are interested:
[](https://github.com/Unity-Technologies/EntityComponentSystemSamples/issues/127#issuecomment-480495932) .

**Comment by DragonMastery** [comment]
I am very interested! @Opeth001
